fix: make icon positioning consistent in searchbox inputs
SAP/open-ux-tools pull request #1046
Opened 2023-05-30 10:47 UTC by oliversberzs

* Fixed the searchbox icon's position not being consistent between projects
* Fixed the searchbox icon moving slightly before disappearing on focus

2023-05-30 17:12 UTC, Klaus-Keller requested changes
Hi @oliversberzs,

I've checked the changes in storybook and after your change the search icon (magnifier) looks slightly misplaced to the top. See this animated gif, it shows after and then before the change. The one in which the magnifier is more to the top is after:

![2023-05-30_10-05-53 (1)](https://github.com/SAP/open-ux-tools/assets/66327622/c3fbafab-4c8d-42bf-8ad7-a74712833998)

Perhaps the consuming app has styles that causes misalignment of the search icon?

2023-06-07 13:14 UTC, Klaus-Keller approved these changes
- style changes look good
- tested locally, no glitch on icon animation when search box get's focus after the fix

Approved from my side.

2023-06-07 13:14 UTC, Klaus-Keller approved these changes
- style changes look good
- tested locally, no glitch on icon animation when search box get's focus after the fix

Approved from my side.

2023-06-07 13:47 UTC, unseen1980 approved these changes

2023-06-07 14:02 UTC, merged