feat: move cds annotation converter package
SAP/open-ux-tools pull request #1609
Opened 2024-01-23 15:47 UTC by nahmed22

Move cds annotation converter module to open-ux-tools repository

2024-01-24 07:48 UTC, vinayhospete submitted a review, later dismissed

2024-01-24 07:49 UTC, vinayhospete commented
Please solve 6 sonar issues (remove TODO comments in code)

2024-01-25 03:27 UTC, vinayhospete submitted a review, later dismissed

2024-01-25 08:16 UTC, voicis submitted a review, later dismissed

2024-01-25 16:53 UTC, kranthie-sap requested changes
The changes to the codeowners file, sonar configuration and root tsconfig.json look good. Please see comment about changeset file.

2024-01-25 16:53 UTC, kranthie-sap commented on .changeset/pretty-coins-leave.md
> +"@sap-ux/cds-odata-annotation-converter": patch
Consider changing this to a minor upgrade.

2024-01-26 14:18 UTC, kranthie-sap commented on .changeset/pretty-coins-leave.md
> +"@sap-ux/cds-odata-annotation-converter": patch
Thanks, @voicis

2024-01-26 14:18 UTC, kranthie-sap approved these changes

2024-01-26 14:22 UTC, voicis approved these changes

2024-01-26 14:22 UTC, merged