feat: implementation for different loader within combobox
SAP/open-ux-tools pull request #1731
Opened 2024-03-06 15:15 UTC by 815are

#1730

2024-03-14 09:50 UTC, vadson71 approved these changes

2024-03-19 14:46 UTC, devinea requested changes
Code changes are clear and covered by tests

typo in changset as below

2024-03-19 14:46 UTC, devinea commented on .changeset/wicked-drinks-return.md
> +UIComboBox. Extender 'isLoading' property with option to set laoding within combobox input.
```suggestion
UIComboBox. Extender 'isLoading' property with option to set loading within combobox input.
```

2024-03-19 14:50 UTC, devinea approved these changes
Thanks. Looks good.

2024-03-19 15:15 UTC, vadson71 approved these changes

2024-03-19 15:49 UTC, merged