feat: Update of JSON files with previous spacing
SAP/open-ux-tools pull request #2011
Opened 2024-06-05 17:36 UTC by broksy

Adds `updatePackageJSON` and `updateManifestJSON` that updates JSON files while keeping the previous indentation/spacing.

2024-06-06 10:53 UTC, Klaus-Keller requested changes
Hi @broksy, 
Please see my comments. There also some minor linting issues.

2024-06-06 10:53 UTC, Klaus-Keller commented on packages/project-access/src/file/file-access.ts
> +import { Manifest, Package } from '../types';
```suggestion
import type { Manifest, Package } from '../types';
```

2024-06-06 10:53 UTC, Klaus-Keller commented on packages/project-access/src/file/file-access.ts
> +export async function updatePackageJSON(path:string, packageJson: Package): Promise<void> {
```suggestion
export async function updatePackageJSON(path: string, packageJson: Package): Promise<void> {
```

2024-06-06 10:53 UTC, Klaus-Keller commented on packages/project-access/src/file/file-access.ts
> + * @param manifest - updated JSON file content
```suggestion
 * @param content - updated JSON file content
```

2024-06-06 10:53 UTC, Klaus-Keller commented on packages/project-access/src/file/file-info.ts
> +import { JSONFileInfo } from "../types";
```suggestion
import type { JSONFileInfo } from '../types';
```

2024-06-06 10:53 UTC, Klaus-Keller commented on packages/project-access/src/types/info/index.ts
> +    // End of file
Could we simplify this to one property `space: number | string` which is the same as described in https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#space?

```suggestion
    // Space as defined in https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#space
    sapce: number | string;
```

2024-06-06 10:53 UTC, Klaus-Keller commented on packages/project-access/src/file/file-info.ts
> +}
If we simplify the structure to have `space` property, this function would be obsolete.

2024-06-06 10:53 UTC, Klaus-Keller commented on packages/project-access/test/file/file-access.test.ts
> +        test('Should update package.json using previous indentation', async () => {
Can we please add some tests for files with different indenting and different characters like spaces or `\t`?

2024-06-11 13:07 UTC, Klaus-Keller requested changes
@broksy, thanks a lot! See some minor comments below.

2024-06-11 13:07 UTC, Klaus-Keller commented on packages/project-access/src/file/file-access.ts
> +    const oldContentText = await readFile(path);
If we add optional parameter `memFs?: Editor`, this line would then become 
```suggestion
    const oldContentText = await readFile(path, memFs);
```

2024-06-11 13:07 UTC, Klaus-Keller commented on packages/project-access/src/file/file-access.ts
> +    await writeFile(path, result);
If we add optional parameter `memFs?: Editor`, this line would then become 
```suggestion
    await writeFile(path, result, memFs);
```

2024-06-11 13:07 UTC, Klaus-Keller commented on packages/project-access/package.json
> +        "json-parse-even-better-errors": "3.0.2",
Shouldn't this be declared in `dependencies`?
Additionally, `@types/json-parse-better-errors` can be added in `devDependencies`

2024-06-12 20:01 UTC, Klaus-Keller commented on packages/project-access/src/project/access.ts
> +        await updatePackageJSON(join(this.app.appRoot, 'package.json'), packageJson, memFs);
Could we add a contant to `packages/project-access/src/constants.ts`

2024-06-12 20:19 UTC, Klaus-Keller requested changes
Hi @broksy, two comments, rest looks good.

2024-06-12 20:19 UTC, Klaus-Keller commented on packages/project-access/package.json
> +        "@types/json-parse-better-errors": "1.0.3",
Sorry @broksy, seems this does not contain correct types, I've misread the package name, we are using json-parse-**even**-better-errors, so we can remove this and keep your declaration file.
```suggestion
```

2024-06-13 12:49 UTC, Klaus-Keller approved these changes
Thanks @broksy!
- code is well structured and easy to understand
- changest exists
- code coverage is great

Approved from my side.

2024-06-13 13:49 UTC, 815are reviewed
Checked:
1. code changes simple to read and understand;
2. tests are added
3. changelog presents

Did not test manually, but noticed small question about line endings

2024-06-13 13:49 UTC, 815are commented on packages/project-access/src/file/file-access.ts
> +    const result = JSON.stringify(content, null, oldContentJson[indent]) + '\n';
@Klaus-Keller 
should we consider `\r\n` line endings?
I think example in https://github.com/npm/json-parse-even-better-errors contains it

2024-06-13 13:49 UTC, 815are approved these changes

2024-06-13 15:55 UTC, merged