feat: Launch config package
SAP/open-ux-tools pull request #2040
Opened 2024-06-17 12:46 UTC by broksy

Introducing package for managing VSCode launch configurations in `.vscode/launch.json`.

2024-07-10 09:19 UTC, Klaus-Keller requested changes
Hi @broksy, could you please check the sonar code smells: https://sonarcloud.io/project/issues?id=SAP_open-ux-tools&pullRequest=2040&resolved=false&sinceLeakPeriod=true

2024-07-10 09:19 UTC, Klaus-Keller commented on packages/launch-config/package.json
> +    "version": "1.0.0",
@broksy, could we start with a 0.x version in case we need changes?
```suggestion
    "version": "0.0.1",
```

2024-07-10 09:25 UTC, Klaus-Keller commented on packages/launch-config/test/test-data/test-workspace/fe-project/cap/srv/incidentservice.js
This file contains only commented out code, can we delete it?

2024-07-12 07:40 UTC, Klaus-Keller requested changes

2024-07-12 07:40 UTC, Klaus-Keller commented on packages/launch-config/src/launch-config-crud/read.ts
> +        console.error(`Could not find launch config '${name}' in '${launchConfigPath}'`, error);
We should avoid usage of `console`. We can either allow to pass in an optional logger, e.g. like done here:
https://github.com/SAP/open-ux-tools/blob/b6782872d18ca4fe459fda6ff61ac293cd4ec7e0/packages/project-access/src/project/specification.ts#L83

If we do it this way, I propose to change the signature of this function to:

```typescript
export async function getLaunchConfigByName(
    launchConfigPath: string,
    name: string,
    options?: { memFs?: Editor; logger?: Logger; }
): Promise<LaunchConfig>
```

Another option is to just throw an error with message and original error, e.g.
```typescript
throw Error(`Could not find launch config '${name}' in '${launchConfigPath}'. Error ${error}`);
```

2024-07-12 07:40 UTC, Klaus-Keller commented on packages/launch-config/src/project-discovery/project.ts
> +        console.error(`Error while getting the default configuration for project '${projectRoot}'`, error);
Please avoid `console`, see other comment

2024-07-12 12:59 UTC, Klaus-Keller approved these changes
Thanks @broksy!
- new module is well structured
- changeset exists
- test coverage is good
- did a manual test, no issues found

Approved from my side.

2024-07-15 14:53 UTC, kjose90 approved these changes
Files are well structured 
Changeset & test coverage ✅ 
Tested locally
Good job @broksy

2024-07-15 15:12 UTC, merged