fix: delete text and textArranmgnet
SAP/open-ux-tools pull request #2109
Opened 2024-07-02 19:15 UTC by nahmed22

Delete Common Text and TextArrangement  (setting value of Text to None")

2024-07-09 14:10 UTC, voicis requested changes

2024-07-09 15:02 UTC, vadson71 commented on packages/fiori-annotation-api/src/cds/preprocessor.ts
> +            return createDeleteAnnotationGroupItemsChange(parentPointer.split('/').slice(0, -1).join('/'));
done

2024-07-09 15:03 UTC, vadson71 commented on packages/fiori-annotation-api/src/cds/preprocessor.ts
> +        const parentPointerForGroup = parentPointer.split('/').slice(0, -1).join('/');
corrected

2024-07-10 09:15 UTC, voicis approved these changes
- Code changes looks good
- Review comments addressed
- Great test coverage

2024-07-10 09:38 UTC, Jimmy-Joseph19 approved these changes
Changes looks - good.
Tested locally.
Test coverage - good.
Approving

2024-07-10 09:43 UTC, merged