Performance/project access/cache global cds module promise
SAP/open-ux-tools pull request #2148
Opened 2024-07-11 16:13 UTC by ManuelPastorini

To load global installed cds module, we use shell command to identify the path to load from. This is quite expensive, and gets even worse if called multiple times in parallel. So far, only after retrieving the path, we cached it to avoid further requests - now, we already cache the promise, thus we can avoid sending the same shell command again, while the first request is still running.

2024-07-17 22:45 UTC, Klaus-Keller requested changes
Hi @ManuelPastorini,
please add a changeset by running 
```
pnpm changeset
```
in root of this repository. I propose a patch update.

2024-07-18 08:45 UTC, ManuelPastorini commented
Hi Klaus,

I added a change-set now. I hope, I did it correctly ;)

2024-07-18 13:48 UTC, Klaus-Keller commented on packages/project-access/src/project/cap.ts
> +        });
Would the async/await notation not be more readable, what do you think?

```suggestion
            const versions = await getCdsVersionInfo();
            if (versions.home) {
                resolve(loadModuleFromProject<CdsFacade>(versions.home, '@sap/cds'));
            } else {
                reject(
                    new Error(
                        'Can not find global installation of module @sap/cds, which should be part of @sap/cds-dk'
                    )
                );
            }
```

2024-07-18 14:24 UTC, Klaus-Keller approved these changes
Thanks @ManuelPastorini,
- code changes to prepare for parallel processing of `cds --version` look good
- changeset exists
- test coverage is great
- did a local test, could not found issues

Approved from my side,

2024-07-18 15:46 UTC, johannes-kolbe approved these changes
- Code looks good, 
- Cache approach sounds good
- Did not test manually

2024-07-18 16:24 UTC, merged