Changed tooltip for green circles
SAP/open-ux-tools pull request #2191
Opened 2024-07-24 14:07 UTC by emrecevik06

Changed the tooltips for the green circles. The green circles indicates the sate of saving(modified & saved, modified & unsaved, saved & unsaved). Those are changed and has now a more specific description.

2024-07-24 16:11 UTC, marufrasully requested changes

2024-07-24 16:11 UTC, marufrasully commented on packages/control-property-editor/src/components/ChangeIndicator.tsx
> +    const type = id == 'sapUshellDashboardPage--ChangeIndicator' ? 'control' : 'property';
@emrecevik06 remove this conditional from here. Extend this interface https://github.com/SAP/open-ux-tools/blob/main/packages/control-property-editor/src/components/ChangeIndicator.tsx#L5
and add pass type information where `ChangeIndicator` is consumed. e.g https://github.com/SAP/open-ux-tools/blob/main/packages/control-property-editor/src/panels/outline/Tree.tsx#L292

2024-07-24 20:06 UTC, marufrasully approved these changes
Thanks @emrecevik06
* Changes look good
* Tests coverage is good
* Comment is addressed

2024-07-25 07:06 UTC, UweSchwerk approved these changes

2024-07-25 07:08 UTC, marufrasully approved these changes

2024-07-25 07:13 UTC, merged