Add sticky search bar for outline and filter search
SAP/open-ux-tools pull request #2197
Opened 2024-07-29 14:45 UTC by emrecevik06

Add sticky search bar for outline and filter search in OutlinePanel and ChangesPanel

2024-07-31 09:03 UTC, gpeuc commented
Be aware that there are some updates to the whole sticky filter inputs in this big issue

https://github.wdf.sap.corp/ux-engineering/tools-suite/issues/30749

2024-07-31 11:10 UTC, marufrasully requested changes

2024-07-31 11:10 UTC, marufrasully commented on packages/control-property-editor/test/unit/panels/changes/ChangesPanel.test.tsx
> +        const searchBar = container.getElementsByClassName('ms-SearchBox root-109');
Please adapt this selector. This may break.

2024-07-31 11:10 UTC, marufrasully commented on packages/control-property-editor/test/unit/panels/changes/ChangesPanel.test.tsx
> +        const searchBar = container.getElementsByClassName('ms-SearchBox can-clear root-165');
see above.

2024-08-01 09:52 UTC, marufrasully approved these changes
Thanks @emrecevik06 
* Changes is simple and straightforward
* Unit test is added
* Comment addressed

2024-08-01 10:22 UTC, Jimmy-Joseph19 approved these changes
Changes looks good.
Tested locally and works as expected.
Approving. Thanks @emrecevik06 for the fix.

2024-08-01 11:18 UTC, merged