fix: adjustment of the color of chevron on selection
SAP/open-ux-tools pull request #2303
Opened 2024-08-29 12:54 UTC by emrecevik06

2024-08-30 06:34 UTC, Jimmy-Joseph19 commented on packages/control-property-editor/src/panels/outline/Tree.tsx
> +                            className={`${chevronTransform} chevron`}
```suggestion
                            className={`${chevronTransform} active-foreground`}
```

2024-08-30 06:48 UTC, Jimmy-Joseph19 approved these changes
Changes looks good.
Changeset found
Approving

2024-08-30 14:36 UTC, voicis requested changes

2024-08-30 14:36 UTC, voicis commented on packages/control-property-editor/src/panels/outline/Tree.tsx
> +                            className={`${chevronTransform} active-foreground`}
I don't think we should add new class for this. We already have a class for selected row that we can use `app-panel-selected-bg` in combination with the row class `tree-row`. All icons in the tree should be handled generically and we shouldn't need to fix  this for each of them, but with current solution extension icons when selected still has wrong colour.

![image](https://github.com/user-attachments/assets/cf7227d6-29db-44e9-b3f7-922e953e91ef)

2024-09-02 12:29 UTC, voicis approved these changes
- Straight forward style change
- Review comments addressed
- Changeset present
- Tested locally

2024-09-02 13:39 UTC, Jimmy-Joseph19 approved these changes
Feedback Changes looks good
Approving

2024-09-02 14:13 UTC, merged