fix(cpe): application mode after reload
SAP/open-ux-tools pull request #2389
Opened 2024-09-19 15:19 UTC by voicis

Fixes #2341 and varius usability fixes

- Disabled QuickActions in navigation mode because some of them are only supported in adaptation mode
- Do not show nested quick action title if there is only one child
- Increased max width for quick actions to fill the available space in the panel

2024-09-24 07:21 UTC, Jimmy-Joseph19 submitted a review, later dismissed
Changes looks good.
Test coverage is good.
Changeset found.
Haven't tested manually
Approving

2024-09-24 11:09 UTC, nikmace requested changes

2024-09-24 11:09 UTC, nikmace commented on packages/preview-middleware-client/types/sap.ui.rta.d.ts
> +        getMode: () => RtaMode;
Is this method available for all ui5 versions or only higher ones? If it's not lower versions will throw error

2024-09-25 07:43 UTC, nikmace commented on packages/preview-middleware-client/types/sap.ui.rta.d.ts
> +        getMode: () => RtaMode;
Checked that it works in lower versions including 1.71.70

2024-09-25 07:43 UTC, nikmace approved these changes
Code looks good
Coverage is good
Did not test manually

2024-09-25 08:11 UTC, Jimmy-Joseph19 approved these changes

2024-09-25 08:12 UTC, merged