fix: add page and table quick actions v2 app
SAP/open-ux-tools pull request #2408
Opened 2024-09-24 14:44 UTC by nahmed22

Add quick-actions to add table and page action

2024-09-30 07:12 UTC, vadson71 requested changes

2024-10-01 08:07 UTC, nikmace requested changes

2024-10-01 11:48 UTC, vadson71 commented on packages/preview-middleware-client/src/adp/controllers/AddFragment.controller.ts
> +    }
Added

2024-10-01 12:27 UTC, vadson71 commented on packages/preview-middleware-client/src/adp/quick-actions/fe-v2/table-quick-action-base.ts
> +    private getTableLabel(table: UI5Element): string {
Added

2024-10-02 07:10 UTC, vadson71 commented on packages/preview-middleware-client/test/unit/adp/quick-actions/fe-v2.test.ts
> +                );
Yes, true. Added missing part

2024-10-02 10:19 UTC, nikmace approved these changes
Code looks good
Comments addressed
Coverage is OK

There are two issues in SonarCloud, 
I think they are false positive ('rta' is deprecated.)

2024-10-02 10:38 UTC, 815are approved these changes
checked:
1. code changes are readable
2. changelog persists

did not test manually

2024-10-02 10:38 UTC, 815are commented on packages/adp-tooling/templates/rta/common/custom-action.xml
> +    <Button text="New Button"  id="<%- ids.toolbarActionButton %>"></Button>
just in case there is two white spaces `text="New Button"  id`, not sure if it is intended

2024-10-02 11:16 UTC, merged