fix: various ui improvements and bug fix
SAP/open-ux-tools pull request #2410
Opened 2024-09-25 13:45 UTC by vadson71

[Issue](https://github.wdf.sap.corp/ux-engineering/tools-suite/issues/31433)
CPE UI changes:
- improved warning texts on popups
- suppressed repetitive warning after preview reload
- improved quick actions styles (long action names are not truncated but wrapped to multiline representation)
- corrected distances between actions, and their groups
- fixed wrong positioning of the action context menu.

2024-09-25 14:59 UTC, Jimmy-Joseph19 commented on .changeset/great-glasses-pump.md
> +---
need to add preview-middleware as well

2024-09-25 15:04 UTC, vadson71 commented on .changeset/great-glasses-pump.md
> +---
Thanks! Added

2024-09-26 10:10 UTC, nikmace requested changes

2024-09-26 12:00 UTC, nikmace approved these changes
Code looks good
Coverage is good
Did not test manually

2024-09-26 13:38 UTC, Jimmy-Joseph19 approved these changes
Thanks for the fixes. 
Changes looks good.
Test coverage good.
Haven't tested manually.
Approving.

2024-09-26 14:54 UTC, merged