feat(ref-lib-gen): adds new module @sap-ux/ui5-library-reference-sub-generator
SAP/open-ux-tools pull request #2512
Opened 2024-10-30 16:32 UTC by cianmSAP

#2472 

 adds new module @sap-ux/ui5-library-reference-sub-generator

2024-10-31 17:12 UTC, cianmSAP commented on packages/ui5-library-reference-sub-generator/src/app/index.ts
> +// eslint-disable-next-line @typescript-eslint/no-explicit-any
Thanks @longieirl , I've tested and it's not required. I've removed

2024-11-01 14:09 UTC, longieirl submitted a review, later dismissed
I havent checked alot of the js files.
The implementation looks good.
Test coverage is good.

2024-11-04 12:03 UTC, devinea requested changes

2024-11-04 12:03 UTC, devinea commented on packages/ui5-library-reference-sub-generator/test/unit/sample/test_project_lrop_not_sapux/ui5.yaml
> +        url: http://ims.saplabs.com:50017
Maybe mock server here?

2024-11-04 12:03 UTC, devinea commented on packages/ui5-library-reference-sub-generator/test/unit/sample/test_project_lrop_v2/ui5-local.yaml
> +        url: http://ims.saplabs.com:50017
remove

2024-11-04 12:03 UTC, devinea commented on packages/ui5-library-reference-sub-generator/test/unit/sample/test_project_lrop_v2/ui5.yaml
> +        url: http://ims.saplabs.com:50017
remove

2024-11-04 12:03 UTC, devinea commented on packages/ui5-library-reference-sub-generator/test/unit/sample/test_project_lrop_v2_custom_webapp_path/ui5-local.yaml
> +        url: http://ims.saplabs.com:50017
remove

2024-11-04 12:03 UTC, devinea commented on packages/ui5-library-reference-sub-generator/test/unit/sample/test_project_lrop_v2_custom_webapp_path/ui5.yaml
> +        url: http://ims.saplabs.com:50017
remove

2024-11-04 14:20 UTC, cianmSAP commented on .changeset/gorgeous-dogs-watch.md
> +'@sap-ux/project-access': patch
Changeset is amended

2024-11-04 17:03 UTC, devinea approved these changes
New module setup looks good. 
Code changes look good. 
Good coverage. 
Changeset ✅ 

Thanks for the updates.

2024-11-05 13:36 UTC, longieirl approved these changes
All comments addressed.
Code coverage is good.
Changeset is now good.
Havent tested locally, only reviewed the implementation code.

2024-11-05 13:38 UTC, merged