feat: expose @sap-ux/jest-environment-ui5
SAP/open-ux-tools pull request #2581
Opened 2024-11-15 15:38 UTC by nlunets

The module is intended to provide a way to test ui5 applications using jest.

This works by creating a custom test environment in which ui5 will be loaded and the test will be run.

The code existed internally before now and this will be notified as such in the Changelog.

2024-11-15 15:53 UTC, nlunets commented on packages/jest-environment-ui5/src/shim/hasher.js
> +							'";</script></head><body>&nbsp;</body></html>'
This file is just a shim of the ui5 code to patch some behavior of the hasher lib that behaves differently when it detects a node environment

2024-11-15 15:53 UTC, nlunets commented on packages/jest-environment-ui5/src/shim/hasher.js
> +					path = path.replace(/\?/, "%3F");
This file is just a shim of the ui5 code to patch some behavior of the hasher lib that behaves differently when it detects a node environment

2024-11-19 09:10 UTC, tobiasqueck requested changes
* why do we need the shims, and is it ok to add the code like that to the repo
* please add a short descriptive comment to each function
* please check your package.json, you refer to the `dist` folder as content (not to `src`) but you don't have a build script (or anything else) that would create `dist`
* please check the lint warnings, all of them are fixable

2024-11-20 09:55 UTC, nlunets commented
Hello @tobiasqueck  
- why do we need the shims, and is it ok to add the code like that to the repo
  -> I found a way to get rid of them 
- please add a short descriptive comment to each function
   -> done
please check your package.json, you refer to the dist folder as content (not to src) but you don't have a build script (or anything else) that would create dist
   -> done
please check the lint warnings, all of them are fixable
   -> kept one that didn't make sense to fix in my opinion

2024-11-21 09:57 UTC, tobiasqueck commented
> Hello @tobiasqueck
> 
> * why do we need the shims, and is it ok to add the code like that to the repo
>   -> I found a way to get rid of them
> * please add a short descriptive comment to each function
>   -> done
>   please check your package.json, you refer to the dist folder as content (not to src) but you don't have a build script (or anything else) that would create dist
>   -> done
>   please check the lint warnings, all of them are fixable
>   -> kept one that didn't make sense to fix in my opinion

Thanks! The code is easier to understand now. Please have a look at the following issues:
* I see one file left in shims, could you please enhance the `/.reuse` file with information where it is from and what you did as well as under which license it is
* could you please use the folders fixtures and unit (in test) for your sample and your tests 
* seems like prettier didn't run on your jest tests
* Shouldn't `jest` be a devDependency since you use it in one of your tests with `const jestCLI = require('jest');`

2024-11-21 11:06 UTC, nlunets commented
@tobiasqueck all done i think :)

2024-11-21 15:08 UTC, tobiasqueck approved these changes
* changeset good
* general project structure adheres to the rest of the repo
* code is understandable - sadly in JS instead of TS but it is ok for now, since this is an existing module
* code is complex but still understandable and maintainable

2024-11-21 15:08 UTC, tobiasqueck commented
@Jimmy-Joseph19 please try if the jest-environment works for you as expected.

2024-11-21 15:21 UTC, tobiasqueck approved these changes

2024-11-25 08:54 UTC, tobiasqueck submitted a review, later dismissed
Re-approving the PR. All changes since the last review improve the code quality and don't affect the functionality.

2024-11-26 15:11 UTC, tobiasqueck approved these changes

2024-11-28 14:40 UTC, voicis approved these changes
@nlunets thanks!
- Tested with a basic scenario in `preview-middleware-client`
- Documentation and error handling could be improved, but that is something we can work in the future

2024-11-28 14:42 UTC, merged