feat: add validations
SAP/open-ux-tools pull request #2603
Opened 2024-11-20 14:40 UTC by GDamyanov

Feat for #2600 

- Additional validations for package prompt

2025-02-04 08:45 UTC, cianmSAP commented on packages/abap-deploy-config-inquirer/src/prompts/conditions.ts
> +    if (PromptState.abapDeployConfig?.scp || (appType === 'Fiori Adaptation' && !PromptState.abapDeployConfig.isS4HC)) {
Why has `hide` & `hideIfOnPremise` options been removed? This prompt would now be hidden for all systems which are `scp` which would be a major change for us.

2025-02-04 08:45 UTC, cianmSAP commented on packages/abap-deploy-config-inquirer/src/prompts/conditions.ts
> +    if (PromptState.transportAnswers.transportRequired === false) {
The first condition on `defaultOrShowTransportQuestion` checks the same thing

2025-02-04 08:45 UTC, cianmSAP commented on packages/abap-deploy-config-inquirer/src/prompts/validators.ts
> +        await getTransportListFromService(input.toUpperCase(), answers.ui5AbapRepo ?? '', backendTarget);
Why are these conditions all dependant on the system being S4HC or FE?
`getTransportListFromService` will no longer be called in a lot of cases?

2025-02-04 09:10 UTC, GDamyanov commented on packages/abap-deploy-config-inquirer/src/prompts/validators.ts
> +        await getTransportListFromService(input.toUpperCase(), answers.ui5AbapRepo ?? '', backendTarget);
Because in our case for onPremise systems we are not prompting for UI5AbapRepo and there is no need to fetch the transports.

2025-02-04 09:28 UTC, cianmSAP commented on packages/abap-deploy-config-inquirer/src/prompts/validators.ts
> +        await getTransportListFromService(input.toUpperCase(), answers.ui5AbapRepo ?? '', backendTarget);
Ok but this change has consequences for all consumers of the inquirer?

2025-02-04 12:23 UTC, GDamyanov commented on packages/abap-deploy-config-inquirer/src/prompts/conditions.ts
> +    if (PromptState.transportAnswers.transportRequired === false) {
Fixed in: [39f7479](https://github.com/SAP/open-ux-tools/pull/2603/commits/39f74792284bcb7ac78d210d3bbfc4d9d09309e7)

2025-02-04 12:56 UTC, GDamyanov commented on packages/abap-deploy-config-inquirer/src/prompts/validators.ts
> +        await getTransportListFromService(input.toUpperCase(), answers.ui5AbapRepo ?? '', backendTarget);
Fixed in [c1a4adb](https://github.com/SAP/open-ux-tools/pull/2603/commits/c1a4adbd9c975c5259f9163557004c1f20b29dab)

2025-02-07 10:21 UTC, cianmSAP commented on packages/abap-deploy-config-inquirer/src/translations/abap-deploy-config-inquirer.i18n.json
> +            "invalidCloudPackage": "The package entered is not meant to be used for cloud deployments.",
```suggestion
            "invalidCloudPackage": "The provided package is not intended for cloud deployments.",
```

2025-02-07 10:21 UTC, cianmSAP commented on packages/abap-deploy-config-inquirer/src/translations/abap-deploy-config-inquirer.i18n.json
> +            "invalidOnpremPackage": "The package entered is not meant to be used for On Premise deployments."
```suggestion
            "invalidOnPremPackage": "The provided package is not intended for on-premise deployments."
```

2025-02-07 10:21 UTC, cianmSAP commented on packages/abap-deploy-config-sub-generator/src/app/index.ts
> +            const appType = await getAppType(this.destinationPath());
I think we can assign the var `isAdp` here and pass this `getAbapQuestions`

2025-02-07 10:21 UTC, cianmSAP commented on packages/abap-deploy-config-sub-generator/src/app/questions.ts
> +    appType?: AppType;
```suggestion
    isAdp = false;
```

2025-02-07 10:47 UTC, cianmSAP commented on packages/abap-deploy-config-sub-generator/src/app/index.ts
> +            const appType = await getAppType(this.destinationPath());
The `appType` from a Fiori gen perspective it could be `SAP Fiori elements`, `SAPUI5 freestyle` or `Fiori Reuse` and we have don't have any specific options for these

2025-02-07 15:03 UTC, GDamyanov commented on packages/abap-deploy-config-inquirer/src/prompts/conditions.ts
> +    if (options?.hideIfOnPremise === true && !PromptState.abapDeployConfig?.isS4HC) {
Fixed in [3638661](https://github.com/SAP/open-ux-tools/pull/2603/commits/3638661fc64e651c12d3f1261f84a2bac9dc5311)

2025-02-07 15:04 UTC, GDamyanov commented on packages/abap-deploy-config-inquirer/src/prompts/index.ts
> +    const appConfigPrompts = getAppConfigPrompts(options);
Fixed in [3638661](https://github.com/SAP/open-ux-tools/pull/2603/commits/3638661fc64e651c12d3f1261f84a2bac9dc5311)

2025-02-07 15:07 UTC, GDamyanov commented on packages/abap-deploy-config-inquirer/src/prompts/conditions.ts
> +        !ui5AbapPromptOptions?.hide &&
Fixed in [6a7798d](https://github.com/SAP/open-ux-tools/pull/2603/commits/6a7798d7cd31c96fdd9213f278c363abb801afc3)

2025-02-07 15:07 UTC, GDamyanov commented on packages/abap-deploy-config-inquirer/src/prompts/validators.ts
>      if (input === DEFAULT_PACKAGE_ABAP) {
Fixed in [3638661](https://github.com/SAP/open-ux-tools/pull/2603/commits/3638661fc64e651c12d3f1261f84a2bac9dc5311)

2025-02-07 15:08 UTC, GDamyanov commented on packages/abap-deploy-config-sub-generator/src/app/index.ts
> +            const appType = await getAppType(this.destinationPath());
Fixed in [3638661](https://github.com/SAP/open-ux-tools/pull/2603/commits/3638661fc64e651c12d3f1261f84a2bac9dc5311)

2025-02-11 11:14 UTC, GDamyanov commented on packages/abap-deploy-config-sub-generator/src/app/questions.ts
> +    isAdp?: boolean;
Fixed in [02969ae](https://github.com/SAP/open-ux-tools/pull/2603/commits/02969aeb77b5cb4b7b9b2b00c0ae1bcbc9fb3167)

2025-02-12 15:10 UTC, longieirl submitted a review, later dismissed
Changes look good.
All issues addressed.
Will be validated when consumed back into tools-suite.
Changeset is good.

2025-03-04 16:15 UTC, lfindlaysap requested changes
@JannaLisa, here is my review.

2025-03-04 16:15 UTC, lfindlaysap commented on packages/abap-deploy-config-inquirer/src/translations/abap-deploy-config-inquirer.i18n.json
>              "abapAppDescLength": "Deployment Description should not exceed 60 characters",
```suggestion
            "abapAppDescLength": "Deployment Description must not exceed 60 characters",
```

2025-03-04 16:15 UTC, lfindlaysap commented on packages/abap-deploy-config-inquirer/src/translations/abap-deploy-config-inquirer.i18n.json
> +            "abapPackageInvalidFormat": "Package name does not match the expected format. Expected format is '/<namespace>/<package_name>'  or just a single package name as a string. If namespace is
```suggestion
            "abapPackageInvalidFormat": "The package name does not match the expected format. The expected format is `/<namespace>/<package_name>`  or a package name. If a namespace is not specified, the package name must start with '$', 'Z', 'Y' or 'SAP'.",
```

2025-03-04 16:15 UTC, lfindlaysap commented on packages/abap-deploy-config-inquirer/src/translations/abap-deploy-config-inquirer.i18n.json
> +            "abapPackageStartingPrefix": "Entered package can start with either namespace, '$', 'Z', 'Y' or 'SAP'",
```suggestion
            "abapPackageStartingPrefix": "The package must start with either a namespace, '$', 'Z', 'Y' or 'SAP'",
```

2025-03-04 16:15 UTC, lfindlaysap commented on packages/abap-deploy-config-inquirer/src/translations/abap-deploy-config-inquirer.i18n.json
>              "abapInvalidNamespace": "Namespace invalid as there are too many forward slashes",
```suggestion
            "abapInvalidNamespace": "The namespace is invalid because there are too many forward slashes.",
```

2025-03-04 16:15 UTC, lfindlaysap commented on packages/abap-deploy-config-inquirer/src/translations/abap-deploy-config-inquirer.i18n.json
>              "abapInvalidNamespaceLength": "Namespace limited to 10 characters, entered {{length}}",
```suggestion
            "abapInvalidNamespaceLength": "The namespace is limited to 10 characters. Entered {{length}}.",
```

2025-03-04 16:15 UTC, lfindlaysap commented on packages/abap-deploy-config-inquirer/src/translations/abap-deploy-config-inquirer.i18n.json
>              "abapInvalidAppNameLength": "Application name limited to 15 characters, entered {{length}}",
```suggestion
            "abapInvalidAppNameLength": "Application name limited to 15 characters. Entered {{length}}.",
```

2025-03-04 16:15 UTC, lfindlaysap commented on packages/abap-deploy-config-inquirer/src/translations/abap-deploy-config-inquirer.i18n.json
>              "abapInvalidAppName": "Application name needs to be prefixed with [{{prefix}}]",
```suggestion
            "abapInvalidAppName": "Application name must be prefixed with [{{prefix}}]",
```

2025-03-04 16:15 UTC, lfindlaysap commented on packages/abap-deploy-config-inquirer/src/translations/abap-deploy-config-inquirer.i18n.json
> +            "charactersForbiddenInPackage": "Only alphanumeric, underscore, $ and slash characters are allowed",
```suggestion
            "charactersForbiddenInPackage": "Only alphanumeric, underscore, $, and slash characters are allowed",
```

2025-03-04 16:15 UTC, lfindlaysap commented on packages/abap-deploy-config-inquirer/src/translations/abap-deploy-config-inquirer.i18n.json
>              "invalidNamespaceLength": "Namespace limited to 10 characters, entered {{length}}",
```suggestion
            "invalidNamespaceLength": "Namespace limited to 10 characters. Entered {{length}}.",
```

2025-03-04 16:15 UTC, lfindlaysap commented on packages/abap-deploy-config-inquirer/src/translations/abap-deploy-config-inquirer.i18n.json
>              "invalidNamespace": "Namespace invalid as there are too many forward slashes",
```suggestion
            "invalidNamespace": "Namespace invalid because there are too many forward slashes",
```

2025-03-04 16:15 UTC, lfindlaysap commented on packages/abap-deploy-config-inquirer/src/translations/abap-deploy-config-inquirer.i18n.json
>              "forbiddenCharacters": "Only alphanumeric, underscore and slash characters are allowed",
```suggestion
            "forbiddenCharacters": "Only alphanumeric, underscore, and slash characters are allowed",
```

2025-03-04 16:15 UTC, lfindlaysap commented on packages/abap-deploy-config-inquirer/src/translations/abap-deploy-config-inquirer.i18n.json
>              "descriptionLength": "Deployment Description should not exceed 60 characters",
```suggestion
            "descriptionLength": "Deployment Description must not exceed 60 characters",
```

2025-03-04 16:15 UTC, lfindlaysap commented on packages/abap-deploy-config-inquirer/src/translations/abap-deploy-config-inquirer.i18n.json
> +            "transportListPreReqs": "Name (SAPUI5 ABAP Repository) and Package are required to retrieve the existing Transport Requests",
```suggestion
            "transportListPreReqs": "Name (SAPUI5 ABAP Repository) and Package are required to retrieve existing transport requests",
```

2025-03-04 16:15 UTC, lfindlaysap commented on packages/abap-deploy-config-inquirer/src/translations/abap-deploy-config-inquirer.i18n.json
> +            "abapInvalidAppNameNamespaceOrStartingPrefix": "Both the SAPUI5 ABAP Repository and the Package that will be used should start in the same way, i.e. a namespace or capital letters 'Z', 'Y
```suggestion
            "abapInvalidAppNameNamespaceOrStartingPrefix": "The SAPUI5 ABAP Repository and Package must start in the same way such as a namespace or capital letters: 'Z', 'Y' or 'SAP'",
```

2025-03-04 16:15 UTC, lfindlaysap commented on packages/abap-deploy-config-inquirer/src/translations/abap-deploy-config-inquirer.i18n.json
> +            "invalidCloudPackage": "The provided package is not intended for cloud deployments.",
```suggestion
            "invalidCloudPackage": "The provided package is not intended for cloud deployment.",
```

2025-03-04 16:15 UTC, lfindlaysap commented on packages/abap-deploy-config-inquirer/src/translations/abap-deploy-config-inquirer.i18n.json
> +            "invalidOnPremPackage": "The provided package is not intended for on-premise deployments."
```suggestion
            "invalidOnPremPackage": "The provided package is not intended for on-premise deployments"
```

2025-03-05 11:31 UTC, JannaLisa reviewed
A few comments, questions and proposals from me.

2025-03-05 11:41 UTC, lfindlaysap commented on packages/abap-deploy-config-inquirer/src/translations/abap-deploy-config-inquirer.i18n.json
> +            "abapPackageInvalidFormat": "Package name does not match the expected format. Expected format is '/<namespace>/<package_name>'  or just a single package name as a string. If namespace is
Updated suggestion.

2025-03-05 11:43 UTC, lfindlaysap commented on packages/abap-deploy-config-inquirer/src/translations/abap-deploy-config-inquirer.i18n.json
> +            "abapPackageStartingPrefix": "Entered package can start with either namespace, '$', 'Z', 'Y' or 'SAP'",
Updated suggestion.

2025-03-05 11:45 UTC, lfindlaysap commented on packages/abap-deploy-config-inquirer/src/translations/abap-deploy-config-inquirer.i18n.json
>              "abapInvalidAppNameLength": "Application name limited to 15 characters, entered {{length}}",
Updated.

2025-03-05 11:45 UTC, lfindlaysap commented on packages/abap-deploy-config-inquirer/src/translations/abap-deploy-config-inquirer.i18n.json
>              "abapInvalidAppName": "Application name needs to be prefixed with [{{prefix}}]",
Updated.

2025-03-05 11:46 UTC, lfindlaysap commented on packages/abap-deploy-config-inquirer/src/translations/abap-deploy-config-inquirer.i18n.json
>              "invalidNamespaceLength": "Namespace limited to 10 characters, entered {{length}}",
Updated.

2025-03-05 11:47 UTC, lfindlaysap commented on packages/abap-deploy-config-inquirer/src/translations/abap-deploy-config-inquirer.i18n.json
> +            "abapInvalidAppNameNamespaceOrStartingPrefix": "Both the SAPUI5 ABAP Repository and the Package that will be used should start in the same way, i.e. a namespace or capital letters 'Z', 'Y
Okay. Updated to use your suggestion.

2025-03-11 12:27 UTC, lfindlaysap requested changes
@GDamyanov, please take a look at the outstanding suggestions. I've reapplied some suggestions that are marked as outdated. Thanks.

2025-03-11 12:27 UTC, lfindlaysap commented on packages/abap-deploy-config-inquirer/src/translations/abap-deploy-config-inquirer.i18n.json
> +            "abapPackageInvalidFormat": "The package name does not match the expected format. The expected format is `/<namespace>/<package_name>`  or a package name. If a namespace is not specified,
```suggestion
            "abapPackageInvalidFormat": "The package name does not match the expected format. The expected format is `/<namespace>/<package_name>` or a package name. If a namespace is not specified, the package name must start with '$', 'Z', 'Y', or 'SAP'.",
```

2025-03-11 12:27 UTC, lfindlaysap commented on packages/abap-deploy-config-inquirer/src/translations/abap-deploy-config-inquirer.i18n.json
> +            "abapInvalidNamespaceLength": "The namespace is limited to 10 characters, but you entered {{length}}.",
```suggestion
            "abapInvalidNamespaceLength": "The namespace is limited to 10 characters. You entered {{length}}.",
```
Reapplying suggestion because it says it is outdated.

2025-03-11 12:38 UTC, lfindlaysap requested changes
@GDamyanov, the following suggestions are still outstanding:
- https://github.com/SAP/open-ux-tools/pull/2603#discussion_r1979767956
- https://github.com/SAP/open-ux-tools/pull/2603#discussion_r1979768317
- https://github.com/SAP/open-ux-tools/pull/2603#discussion_r1979768713
- https://github.com/SAP/open-ux-tools/pull/2603#discussion_r1979769160
- https://github.com/SAP/open-ux-tools/pull/2603#discussion_r1979770086
- https://github.com/SAP/open-ux-tools/pull/2603#discussion_r1979770320

2025-03-11 12:43 UTC, GDamyanov commented on packages/abap-deploy-config-inquirer/src/translations/abap-deploy-config-inquirer.i18n.json
>              "abapInvalidAppNameLength": "Application name limited to 15 characters, entered {{length}}",
Suggestion accepted

2025-03-11 12:44 UTC, GDamyanov commented on packages/abap-deploy-config-inquirer/src/translations/abap-deploy-config-inquirer.i18n.json
>              "charactersForbiddenInAppName": "Only alphanumeric, underscore and slash characters are allowed",
Suggestion accepted

2025-03-11 12:44 UTC, GDamyanov commented on packages/abap-deploy-config-inquirer/src/translations/abap-deploy-config-inquirer.i18n.json
> +            "charactersForbiddenInPackage": "Only alphanumeric, underscore, $ and slash characters are allowed",
Suggestion accepted

2025-03-11 12:45 UTC, GDamyanov commented on packages/abap-deploy-config-inquirer/src/translations/abap-deploy-config-inquirer.i18n.json
>              "invalidNamespace": "Namespace invalid as there are too many forward slashes",
Suggestion accepted

2025-03-11 12:45 UTC, GDamyanov commented on packages/abap-deploy-config-inquirer/src/translations/abap-deploy-config-inquirer.i18n.json
>              "forbiddenCharacters": "Only alphanumeric, underscore and slash characters are allowed",
Suggestion accepted

2025-03-11 12:46 UTC, GDamyanov commented
> @GDamyanov, the following suggestions are still outstanding:
> 
> * [feat: Adapt Deploy Config Inquirer and Deploy Config Sub Generator to support ADP Projects #2603 (comment)](https://github.com/SAP/open-ux-tools/pull/2603#discussion_r1979767956)
> * [feat: Adapt Deploy Config Inquirer and Deploy Config Sub Generator to support ADP Projects #2603 (comment)](https://github.com/SAP/open-ux-tools/pull/2603#discussion_r1979768317)
> * [feat: Adapt Deploy Config Inquirer and Deploy Config Sub Generator to support ADP Projects #2603 (comment)](https://github.com/SAP/open-ux-tools/pull/2603#discussion_r1979768713)
> * [feat: Adapt Deploy Config Inquirer and Deploy Config Sub Generator to support ADP Projects #2603 (comment)](https://github.com/SAP/open-ux-tools/pull/2603#discussion_r1979769160)
> * [feat: Adapt Deploy Config Inquirer and Deploy Config Sub Generator to support ADP Projects #2603 (comment)](https://github.com/SAP/open-ux-tools/pull/2603#discussion_r1979770086)
> * [feat: Adapt Deploy Config Inquirer and Deploy Config Sub Generator to support ADP Projects #2603 (comment)](https://github.com/SAP/open-ux-tools/pull/2603#discussion_r1979770320)

@lfindlaysap all suggestions are accepted.

2025-03-11 12:56 UTC, lfindlaysap approved these changes
@GDamyanov. thanks for making the changes.

2025-03-11 15:19 UTC, cianmSAP commented on packages/abap-deploy-config-inquirer/src/prompts/conditions.ts
> +        (transportInputChoice === TransportChoices.EnterManualChoice || !transportInputChoice)
What is the reason for the addition of `|| !transportInputChoice` ?

2025-03-11 15:23 UTC, cianmSAP commented on packages/abap-deploy-config-inquirer/src/prompts/questions/config/package.ts
> +                defaultPackage(previousAnswers.packageManual ?? options.packageManual?.default, options?.packageManual),
I'll need to test this, I think it could raise issues if a user has entered an empty string and then back navigates. We tend to user `||` due to empty strings being deemed falsy with `??`

2025-03-11 15:43 UTC, cianmSAP commented on packages/deploy-config-sub-generator/src/app/index.ts
> +            this.target = target ?? TargetName.ABAP;
What's the reason for this? I'd prefer we have a default option for the target prompt which is configurable in options

2025-03-11 18:35 UTC, GDamyanov commented on packages/abap-deploy-config-inquirer/src/prompts/conditions.ts
> +        (transportInputChoice === TransportChoices.EnterManualChoice || !transportInputChoice)
Because there is an option for hiding the transport input choice for onPremise systems and the value is undefined.

2025-03-11 18:38 UTC, GDamyanov commented on packages/abap-deploy-config-inquirer/src/prompts/questions/config/package.ts
> +                defaultPackage(previousAnswers.packageManual ?? options.packageManual?.default, options?.packageManual),
Fixed in [905c8bf](https://github.com/SAP/open-ux-tools/pull/2603/commits/905c8bfdd779566edf40a7fca8bcc1620abfec9a) .This change with ?? was done because it cause a sonar code smell.

2025-03-12 11:13 UTC, GDamyanov commented on packages/abap-deploy-config-inquirer/src/prompts/conditions.ts
> +        (transportInputChoice === TransportChoices.EnterManualChoice || !transportInputChoice)
Fixed in [292b1b1](https://github.com/SAP/open-ux-tools/pull/2603/commits/292b1b1d1655a8c4255c2930b195aa2b3e0cd854)

2025-03-12 11:18 UTC, GDamyanov commented on packages/deploy-config-sub-generator/src/app/index.ts
> +            this.target = target ?? TargetName.ABAP;
When the Deploy Target prompt is hidden and has default value then in withCondition function used for filtering prompts for the different targets the deployTarget answer does not exists in the answers and the filter is not working.

2025-03-12 11:19 UTC, GDamyanov commented on packages/abap-deploy-config-inquirer/src/translations/abap-deploy-config-inquirer.i18n.json
> +            "invalidNamespace": "The namespace is invalid because there are too many forward slashes.",
It is not.

2025-03-12 14:35 UTC, cianmSAP commented on packages/deploy-config-sub-generator/src/prompts/sub-gen.ts
>      const { prompts: abapPrompts, answers: abapAnswers } = await getAbapQuestions({
Could we update `getAbapQuestions` so prompt options includes `indexGenerationAllowed` `showOverwriteQuestion` and not as separate params

2025-03-13 13:01 UTC, GDamyanov commented on packages/deploy-config-sub-generator/src/app/index.ts
> +        const appType = await getAppType(this.options.appRootPath);
Fixed in [1ef9bfa](https://github.com/SAP/open-ux-tools/pull/2603/commits/1ef9bfa242c3f69a2c594cc757548b9e4d21e1ed)

2025-03-13 13:57 UTC, GDamyanov commented on packages/abap-deploy-config-inquirer/src/translations/abap-deploy-config-inquirer.i18n.json
> +            "invalidNamespace": "The namespace is invalid because there are too many forward slashes.",
Fixed in [1f5eb30](https://github.com/SAP/open-ux-tools/pull/2603/commits/1f5eb30acf4a975f09c5018c2c60bc900706ab57)

2025-03-14 12:32 UTC, cianmSAP commented on packages/deploy-config-sub-generator/src/app/index.ts
> +            this.target = target ?? TargetName.ABAP;
Thanks for removing

2025-03-14 12:33 UTC, cianmSAP approved these changes
Thanks @GDamyanov 

- Comments addressed
- Test coverage is good
- Changeset present 
- Updates mainly in abap sub gen and inquirer

2025-03-14 14:18 UTC, lfindlaysap submitted a review, later dismissed

2025-03-14 14:33 UTC, longieirl commented on packages/abap-deploy-config-inquirer/src/prompts/questions/abap-target.ts
> +        validate: async (url: string): Promise<boolean | string> => validateUrl(url)
Why is this changed to an async method?

2025-03-17 07:45 UTC, GDamyanov commented on packages/abap-deploy-config-inquirer/src/prompts/questions/abap-target.ts
> +        validate: async (url: string): Promise<boolean | string> => validateUrl(url)
Fixed in [9df50d8](https://github.com/SAP/open-ux-tools/pull/2603/commits/9df50d82d3ccfb9e9cf0859b9110efb13baa1fb0)

2025-03-18 08:52 UTC, longieirl submitted a review, later dismissed
Changes look good.
Comments addressed.
Havent validated localy.

2025-03-18 08:53 UTC, cianmSAP submitted a review, later dismissed
Re-approving

2025-03-18 15:31 UTC, lfindlaysap requested changes
@GDamyanov, I have created some suggestions based on @JannaLisa's review. Please commit them and then the PR is good to go from UA.

2025-03-18 15:31 UTC, lfindlaysap commented on packages/abap-deploy-config-inquirer/src/translations/abap-deploy-config-inquirer.i18n.json
> +            "invalidOnPremSystem": "You have selected a Cloud system, but you previously created project residing on an On-Premise system. Please select an On-Premise system to proceed with the deplo
```suggestion
            "invalidOnPremSystem": "You have selected a cloud system, but you previously created a project residing on an on-premise system. Please select an on-premise system to proceed with the deployment.",
```

2025-03-18 15:31 UTC, lfindlaysap commented on packages/abap-deploy-config-inquirer/src/translations/abap-deploy-config-inquirer.i18n.json
> +            "invalidCloudSystem": "You have selected an On-Premise system, but you previously created project residing on a Cloud system. Please select a Cloud system to proceed with the deployment."
```suggestion
            "invalidCloudSystem": "You have selected an on-premise system, but you previously created a project residing on a cloud system. Please select a cloud system to proceed with the deployment."
```

2025-03-18 15:31 UTC, lfindlaysap commented on packages/abap-deploy-config-inquirer/src/translations/abap-deploy-config-inquirer.i18n.json
> +            "invalidOnPremSystem": "You have selected a Cloud system, but you previously created project residing on an On-Premise system. Please select an On-Premise system to proceed with the deplo
Created suggestion.

2025-03-18 15:31 UTC, lfindlaysap commented on packages/abap-deploy-config-inquirer/src/translations/abap-deploy-config-inquirer.i18n.json
> +            "invalidCloudSystem": "You have selected an On-Premise system, but you previously created project residing on a Cloud system. Please select a Cloud system to proceed with the deployment."
Created suggestion.

2025-03-18 16:05 UTC, lfindlaysap approved these changes
@GDamyanov, thanks for making the changes.

2025-03-19 07:46 UTC, JannaLisa commented
Thanks @GDamyanov, looks good now!

2025-03-19 07:49 UTC, JannaLisa approved these changes
Good to go now!

2025-03-19 12:23 UTC, longieirl submitted a review, later dismissed
re-approving.

2025-03-19 12:44 UTC, cianmSAP approved these changes

2025-03-19 13:59 UTC, donal-tobin-sap submitted a review, later dismissed
Looks to be fine from devops side.

2025-03-19 14:01 UTC, IainSAP commented on packages/abap-deploy-config-inquirer/src/index.ts
> +    AbapServiceProviderManager.resetIsDefaultProviderAbapCloud();
What does this mean? `AbapServiceProviderManager.resetIsDefaultProviderAbapCloud`

2025-03-19 15:43 UTC, tobiasqueck requested changes
ONLY reviewed the changes of the `create` module
* code is clear and easy to understand
* tests are missing: I would expect two tests, one with isAdp true and one with false or undefined

2025-03-19 21:22 UTC, Klaus-Keller commented on packages/abap-deploy-config-inquirer/src/prompts/questions/config/package.ts
> +                defaultPackage(previousAnswers.packageManual || options.packageManual?.default, options?.packageManual),
I saw the [SonarQube code smell](https://sonarcloud.io/project/issues?issueStatuses=ACCEPTED&pullRequest=2603&id=SAP_open-ux-tools&open=AZWGgx2SSqUDach4NQf4) for this line and read the comment from @cianmSAP:
"Empty strings may be valid". 
Don't fully get this, if we use `||` an empty string would be `false` and `options.packageManual?.default` is used.
If a string value is fine, I would expect to use `??` and the code smell would be valid and have to  be fixed. Otherwise, if empty string is a valid value, I'd propose to do:
```suggestion
                defaultPackage(typeof previousAnswers.packageManual === 'string' ? previousAnswers.packageManual : options.packageManual?.default, options?.packageManual),
```
to make it clear.

2025-03-20 12:50 UTC, tobiasqueck approved these changes

2025-03-20 13:17 UTC, cianmSAP commented on packages/abap-deploy-config-inquirer/src/prompts/questions/config/package.ts
> +                defaultPackage(previousAnswers.packageManual || options.packageManual?.default, options?.packageManual),
Sorry, my comment was innacurate. 
The issue with `??` specifically with yeoman is that if a question is not answered it still resolves the answer to be an empty string, rather than undefined. So we have encountered issues where the empty string is either used for defaults, or answers, when it should not.

2025-03-20 14:08 UTC, lfindlaysap approved these changes

2025-03-20 14:50 UTC, merged