feat: introduce ADP FLP config generator
SAP/open-ux-tools pull request #2730
Opened 2024-12-20 13:53 UTC by mmilko01

2025-01-07 12:52 UTC, nikmace requested changes
Overall code the new package looks good

2025-01-07 12:52 UTC, nikmace commented on packages/adp-flp-config-sub-generator/src/app/index.ts
> +        this.launchFlpConfigAsSubGenerator = Boolean(opts.launchFlpConfigAsSubGenerator);
You can just use shorthand "!!"
```suggestion
        this.launchFlpConfigAsSubGenerator = !!opts.launchFlpConfigAsSubGenerator;
```

Some ideas (optional):
It would be good to shorten this variable for readability, flp is contextually understood. 
For example: `launchAsSubGen`. 

And then we could add a comment on what this variable is for above where all of the properties are defined.

2025-01-07 12:52 UTC, nikmace commented on packages/adp-flp-config-sub-generator/src/app/index.ts
> +            AdpFlpConfigLogger.logger.error(t('error.writingPhase', { error }));
`AdpFlpConfigLogger.logger` is repeated too many times instead you could make a new property and just call `this.logger`

2025-01-07 12:52 UTC, nikmace commented on packages/adp-flp-config-sub-generator/src/app/index.ts
> +        }
The constructor is initializing a lot of dependencies, including prompts and callbacks. And is becoming quite big, so maybe it is good to extract some of the logic into its own method like: `_setupPrompts`?

```ts
if (!this.launchAsSubGen) {
    this._setupPrompts();
}
```

2025-01-07 12:52 UTC, nikmace commented on packages/adp-flp-config-sub-generator/src/app/index.ts
> +            configuredSystem = (await systemService.read(backendSystem))?.name;
I think you could use here this method `getCredentialsFromStore` from `@system-access` module:

```ts
import { getCredentialsFromStore } from '@sap-ux/system-access';
```

2025-01-07 12:52 UTC, nikmace commented on packages/adp-flp-config-sub-generator/src/utils/i18n.ts
> +const ui5LibI18nNamespace = 'ui5-library-reference-sub-generator';
This needs to be adjusted to match the name of this flp generator

2025-01-07 12:52 UTC, nikmace commented on packages/odata-service-inquirer/src/prompts/datasources/sap-system/system-selection/questions.ts
> +                // TODO: Show message when connection is successful
Is this comment still needed?

2025-01-08 09:15 UTC, mmilko01 commented on packages/adp-flp-config-sub-generator/jest.config copy.js
> +const config = require('../../jest.base');
Fixed with: dfd39c846aab0d51263f83d5b1db13cc9c81ceab

2025-01-08 11:17 UTC, mmilko01 commented on packages/adp-flp-config-sub-generator/src/app/index.ts
> +        this.launchFlpConfigAsSubGenerator = Boolean(opts.launchFlpConfigAsSubGenerator);
Fixed in: 575d3a5e06ff953c7b3ce6d1886e72fc4a7190b9

2025-01-08 11:24 UTC, mmilko01 commented on packages/adp-flp-config-sub-generator/src/app/index.ts
> +            AdpFlpConfigLogger.logger.error(t('error.writingPhase', { error }));
Fixed in: 2948e91e8ae27c990d7f09ad9b0371a35d31edb7

2025-01-08 11:31 UTC, mmilko01 commented on packages/adp-flp-config-sub-generator/src/app/index.ts
> +        }
Fixed in: 8a84433d2f8c5e9900c47be8e2a4b07d031a8356

2025-01-08 11:34 UTC, mmilko01 commented on packages/adp-flp-config-sub-generator/src/utils/i18n.ts
> +const ui5LibI18nNamespace = 'ui5-library-reference-sub-generator';
Fixed in: 2c6ee78c8417a257a670d60302ae59042efb3248

2025-01-08 11:35 UTC, mmilko01 commented on packages/odata-service-inquirer/src/prompts/datasources/sap-system/system-selection/questions.ts
> +                // TODO: Show message when connection is successful
Yes, the implementation here still needs to be confirmed

2025-01-08 11:48 UTC, mmilko01 commented on packages/adp-flp-config-sub-generator/src/app/index.ts
> +            configuredSystem = (await systemService.read(backendSystem))?.name;
Fixed in: 59b3ce91e4077e309adc852650d560c8b7a228ae

2025-01-21 15:27 UTC, mmilko01 commented on packages/adp-flp-config-sub-generator/src/app/index.ts
> +        } else {
Add validation for Destination existing in the SAP BTP subaccount

2025-01-31 11:09 UTC, IainSAP commented on packages/inquirer-common/src/prompts/credentials.ts
> +                if (additionalValidation) {
There is already a mechanism to add additional validation, additionalMessages in this module : https://github.com/SAP/open-ux-tools/blob/main/packages/inquirer-common/src/prompts/helpers.ts#L40 this keeps the prompts cleaner. 

See https://github.com/search?q=repo%3ASAP%2Fopen-ux-tools%20extendWithOptions&type=code for example usgae. Would be good to keep the same pattern across the  prompting modules. i.e. Pass a prompt specific option with the function to apply.

2025-01-31 11:09 UTC, IainSAP commented on packages/inquirer-common/src/types.ts
> +export interface PasswordQuestion<A extends Answers = Answers> extends BasePasswordQuestion<A> {
This type already exists, https://github.com/SAP/open-ux-tools/pull/2730/files#diff-c4ce7e35ef261ec27c934f9c6ebd3a6e52a3c3e12f434e10786180601e5c6698R88

2025-01-31 11:23 UTC, mmilko01 commented on packages/inquirer-common/src/prompts/credentials.ts
> +                if (additionalValidation) {
I check this option in the past, and we also discussed it, but the problem is that this `extendValidate` doesn't support `async` functions as additional validation.

2025-01-31 11:25 UTC, mmilko01 commented on packages/inquirer-common/src/types.ts
> +export interface PasswordQuestion<A extends Answers = Answers> extends BasePasswordQuestion<A> {
I couldn't find the type, the URL you mentioned in your comments leads to this pull request. Could you please check if it wasn't a copy/paste issue and send me where the type already exists in the project?

2025-01-31 11:39 UTC, IainSAP commented on packages/inquirer-common/src/types.ts
> +export interface PasswordQuestion<A extends Answers = Answers> extends BasePasswordQuestion<A> {
https://github.com/SAP/open-ux-tools/blob/main/packages/inquirer-common/src/types.ts#L88

2025-01-31 11:46 UTC, IainSAP commented on packages/inquirer-common/src/prompts/credentials.ts
> +                if (additionalValidation) {
I think this is something we should add. I can take a look when I get a chance, we could provide an overloaded function that runs as promise or not depending. We can update this in a later PR?

2025-01-31 11:49 UTC, mmilko01 commented on packages/inquirer-common/src/prompts/credentials.ts
> +                if (additionalValidation) {
Sure, It would be great to have a similar implementation for such cases. I think it we could amend this in a later PR, once we have the overloaded function

2025-01-31 11:56 UTC, mmilko01 commented on packages/inquirer-common/src/types.ts
> +export interface PasswordQuestion<A extends Answers = Answers> extends BasePasswordQuestion<A> {
I see, it was recently introduced and I needed to refresh my local branch. Thanks for the info!
Fixed in: 9bd7b50d29001c6bbc99549c04f12a20165ddd6d

2025-01-31 12:43 UTC, mmilko01 commented on packages/i18n/src/write/properties/create.ts
> +    if (!fs?.exists(i18nFilePath) && !(await doesExist(i18nFilePath))) {
If I understand your comment correctly, you prefer to have a check whether `fs` instance is passed and check there and if not passed check in the real file system. Basically, split this condition based on `fs` being passed?

2025-02-03 13:44 UTC, mmilko01 commented on packages/i18n/src/write/properties/create.ts
> +    if (!fs?.exists(i18nFilePath) && !(await doesExist(i18nFilePath))) {
Fixed with: e8bdee04093ce08657d7fa6cef8189659984daf7
Tests added with: ecd6340362f1736945876185f3719dfafc6db068

2025-02-04 10:01 UTC, voicis approved these changes
- changes to i18n package looks good
- review comments addressed
- good test coverage
- did not test locally

2025-02-04 12:44 UTC, devinea approved these changes
New module @sap-ux/adp-flp-config-sub-generator setup looks good.

2025-02-04 13:34 UTC, nikmace requested changes
Overall looks good, just some minor comments.

2025-02-05 08:14 UTC, mmilko01 commented on packages/adp-flp-config-sub-generator/src/app/index.ts
> +        opts.force = true;
Fixed in: 1f81c49e037a234a3a4caee73a36a53eb23cddf6

2025-02-05 09:09 UTC, nikmace commented on packages/adp-flp-config-sub-generator/src/translations/adp-flp-config-sub-generator.i18n.json
> +        "projectNotSupported": "Unable to find a supported adaptation project",
Discussed in a meeting

2025-02-05 09:24 UTC, mmilko01 commented on packages/adp-flp-config-sub-generator/src/app/index.ts
> +        addi18nResourceBundle();
Both points fixed in: 1befebb9d178fb9b8b91418f4a3837f5eb7605b7

2025-02-05 09:31 UTC, mmilko01 commented on packages/adp-flp-config-sub-generator/src/app/index.ts
> +            requiestOptions['auth'] = { username: this.credentials.username, password: this.credentials.password };
Fixed in: b73b3a7eefeca3d85941bf8c988930d20f76ade5

2025-02-05 09:34 UTC, mmilko01 commented on packages/adp-flp-config-sub-generator/test/app.test.ts
> +        showInformationSpy.mockReset();
Fixed in: bd4b61e3380dbe58d46415ca86f2fcec4f4a0370

2025-02-05 11:13 UTC, nikmace approved these changes
Code looks good
Changeset is good
Coverage is good
Did not test manually

2025-02-05 11:15 UTC, voicis approved these changes
re-approving, no changes for i18n related code.

2025-02-05 14:43 UTC, devinea approved these changes
re-approving new module setup

2025-02-05 16:44 UTC, merged