fix: avoid double delimiters
SAP/open-ux-tools pull request #291
Opened 2022-01-26 17:39 UTC by slin-sap

2022-01-26 19:15 UTC, devinea submitted a review, later dismissed
Lgtm

2022-01-26 22:20 UTC, ullasholla commented on packages/fiori-freestyle-writer/src/packageConfig.ts
> +    const params = `${searchParam}${harshFragment}`;
`harshFragment` -> `hashFragment` or even just `fragment` or `urlFragment`?

2022-01-26 22:57 UTC, ullasholla requested changes
Looks good, other than that typo. Cheers.

2022-01-26 23:19 UTC, ullasholla commented
Looks good, @slin-sap, thank you. Thanks for using `URLSearchParams` to build up the search string.

2022-01-26 23:19 UTC, ullasholla approved these changes

2022-01-27 00:29 UTC, devinea approved these changes

2022-01-27 00:30 UTC, merged

2022-01-27 10:05 UTC, IainSAP reviewed
Thx @slin-sap

2022-01-27 10:35 UTC, IainSAP commented on packages/fiori-freestyle-writer/src/packageConfig.ts
> +    searchParam = searchParam ? `?${searchParam}` : '';
Unnecessary condition since `searchParamList` always has a value.