fix(security): upgrade keytar
SAP/open-ux-tools pull request #304
Opened 2022-02-02 20:59 UTC by donal-tobin-sap

- fixes simple-get vulnerability

2022-02-02 22:00 UTC, devinea submitted a review, later dismissed

2022-02-02 22:15 UTC, ullasholla approved these changes
Thanks Donal.

This is the advisory: https://github.com/advisories/GHSA-wpg7-2c88-r8xv

2022-02-02 22:16 UTC, ullasholla requested changes
Does this need a changeset?

2022-02-03 09:24 UTC, devinea approved these changes

2022-02-03 16:09 UTC, ullasholla approved these changes
Thanks for this fix @donal-tobin-sap

2022-02-03 20:39 UTC, merged