tbi: telemetry settings store
SAP/open-ux-tools pull request #362
Opened 2022-03-01 18:33 UTC by slin-sap

2022-03-02 13:38 UTC, tobiasqueck commented on packages/store/src/entities/telemetry-setting.ts
> +/** This represents the migration status of the systems from pure secure store
I don't understand this comment

2022-03-02 13:50 UTC, tobiasqueck requested changes
Link to actual issue is missing (I am assuming it is #358) and neither issue nor PR contain sufficient information to understand why this is done.

2022-03-04 19:39 UTC, ullasholla approved these changes
Thanks @slin-sap, looks good. Test coverage is good too.

2022-03-07 19:07 UTC, tobiasqueck approved these changes
The code is simple and well structured. I am missing comments for each function, however, since the functions are self-explanatory I am not seeing it as a reason to block the merge.

2022-03-07 19:49 UTC, merged