chore(open-ux-tools) - limit dependabot PR's
SAP/open-ux-tools pull request #496
Opened 2022-05-17 21:09 UTC by devinea

limit dependabot PR's to reduce spam. As updates are being done manually currently.
dependabot is not currently very useful as it is missing support for pnpm which may come in 2022.
https://github.com/dependabot/dependabot-core/issues/1736#issuecomment-1095558364

2022-07-21 13:43 UTC, IainSAP commented on .github/dependabot.yml
> +          day: 'monday'
Would the weekend be more appropriate?

2022-07-21 14:30 UTC, kranthie-sap approved these changes
Looks good to me. Thanks.

2022-07-22 17:02 UTC, ullasholla requested changes
Thanks @devinea, the changes look good.

However, does it make sense to stop dependabot from creating PRs if it not support pnpm yet?

2022-07-22 17:24 UTC, devinea commented
> Thanks @devinea, the changes look good.
> 
> However, does it make sense to stop dependabot from creating PRs if it not support pnpm yet?

@ullasholla https://github.com/SAP/open-ux-tools/pull/496/files#diff-243ea1a69df2888daa031a562e888a97d4a5a118147aab43c8c8d26c70e26499 should provide a workaround for the missing pnpm support.

2022-07-22 21:32 UTC, ullasholla commented
> > Thanks @devinea, the changes look good.
> > However, does it make sense to stop dependabot from creating PRs if it not support pnpm yet?
> 
> @ullasholla https://github.com/SAP/open-ux-tools/pull/496/files#diff-243ea1a69df2888daa031a562e888a97d4a5a118147aab43c8c8d26c70e26499 should provide a workaround for the missing pnpm support.

Thanks. Do you mind updating the PR description with this information? It's not very obvious otherwise

2022-07-22 23:07 UTC, devinea commented
> > > Thanks @devinea, the changes look good.
> > > However, does it make sense to stop dependabot from creating PRs if it not support pnpm yet?
> > 
> > 
> > @ullasholla https://github.com/SAP/open-ux-tools/pull/496/files#diff-243ea1a69df2888daa031a562e888a97d4a5a118147aab43c8c8d26c70e26499 should provide a workaround for the missing pnpm support.
> 
> Thanks. Do you mind updating the PR description with this information? It's not very obvious otherwise

Updated @ullasholla

2022-07-25 15:22 UTC, ullasholla approved these changes
Thanks @devinea

2022-07-25 15:22 UTC, merged

2022-08-01 10:08 UTC, tobiasqueck commented
@devinea it looks like you added `open-pull-requests-limit: 5` twice to the config. Could you please fix it when time permits. Absolutely NOT urgent, just like to get it fixed before change it again, and miss the 2nd setting

2022-08-02 12:39 UTC, devinea commented
> @devinea it looks like you added `open-pull-requests-limit: 5` twice to the config. Could you please fix it when time permits. Absolutely NOT urgent, just like to get it fixed before we change it again, and miss the 2nd setting

@tobiasqueck That is correct. The limit is under 2 different objects in the config. `- package-ecosystem: 'github-actions'` and `- package-ecosystem: 'npm'`

2022-08-02 12:50 UTC, tobiasqueck commented
@devinea sorry, I missed that.
(I hate yaml!)