Fixing multiple issues with the layered repository service
SAP/open-ux-tools pull request #637
Opened 2022-08-24 13:49 UTC by tobiasqueck

2022-08-24 15:57 UTC, testojs submitted a review, later dismissed
Looks great! Thanks Tobias!

2022-08-24 16:16 UTC, testojs submitted a review, later dismissed

2022-08-25 01:45 UTC, ullasholla commented on examples/odata-cli/README.adoc
> +This project contains scripts to fetch OData metadata and annotations from using the `@sap-ux/axios-extension` and `@sap-ux/btp-utils` modules with real environments. It also contains scripts showing
```suggestion
This project contains scripts to fetch OData metadata and annotations by using the `@sap-ux/axios-extension` and `@sap-ux/btp-utils` modules with real environments. It also contains scripts showing how to work with the layered repository service and the ADT services.
```
Does sound better?

2022-08-25 04:01 UTC, ullasholla requested changes
Thanks @tobiasqueck, looks good. Had a minor note about the `README`: https://github.com/SAP/open-ux-tools/pull/637/files#r954428623

2022-08-25 06:33 UTC, ullasholla approved these changes
Thanks @tobiasqueck

2022-08-25 07:55 UTC, merged