fix(uic): fixes jumping cursor in editable table input
SAP/open-ux-tools pull request #863
Opened 2023-01-10 15:53 UTC by tom-sap

Fixes jumping cursor in UITable inputs with validation.

2023-01-11 11:21 UTC, 815are submitted a review, later dismissed
Code looks ok(small comment regarding `any` usage).
Tested with storybook - did not notice issues.

@tom-sap 
Test coverage - can we improve test coverage?

2023-01-11 11:21 UTC, 815are commented on packages/ui-components/src/components/UITable/UITable.tsx
> +        const newState: any = {};
maybe we can avoid usage of `any`?

2023-01-11 12:12 UTC, tom-sap commented on packages/ui-components/src/components/UITable/UITable.tsx
> +        const newState: any = {};
fixed, thanks!

2023-01-11 14:56 UTC, tom-sap commented
as for the coverage, it was already low, and I only added 4 lines physically. The rest is just moving lines out of 1 function to another function, because another smart-bot complained that it was too complex. 
This issue already took more time than necessary, and we just don't have the capacity to write all the tests required for the component, as a part of this fix.

2023-01-11 16:25 UTC, Klaus-Keller commented
> as for the coverage, it was already low, and I only added 4 lines physically. The rest is just moving lines out of 1 function to another function, because another smart-bot complained that it was too complex. This issue already took more time than necessary, and we just don't have the capacity to write all the tests required for the component, as a part of this fix.

Hi @tom-sap,

1. Coverage is measured on [new lines](https://sonarcloud.io/component_measures?metric=new_coverage&selected=SAP_open-ux-tools%3Apackages%2Fui-components%2Fsrc%2Fcomponents%2FUITable%2FUITable.tsx&view=list&pullRequest=863&id=SAP_open-ux-tools) of code only, not the whole module.
2. If you move code, e.g. to reduce cognitive complexity, it would be a great opportunity to add missing tests for the small part of the code that has moved.

2023-01-12 15:18 UTC, tom-sap commented
Hi @Klaus-Keller,

I've spent several hours trying to make the tests work for this new feature, but it looks like it's not possible. Jest & enzyme just don't have the ability to test such low-level functionality. They can fake-trigger events (by calling the event listeners) but that doesn't actually update the DOM in the same way as the user interactions would.
I can update the input value, but that's not sufficient to test the interaction.

Basically the interaction works like this:
- user starts editing the field in a column that has validation
- user moves the caret inside the input to the beginning of the value text
- user removes a character from the value which triggers the validation error
- the caret stays in the same position after component is re-rendered

Unless there's a way to access the HTML Element of the input (which I haven't found) and trigger events directly to this element - I see no way of unit-testing this.

2023-01-12 15:31 UTC, devinea commented
> I've spent several hours trying to make the tests work for this new feature, but it looks like it's not possible. Jest & enzyme just don't have the ability to test such low-level functionality. 

@tom-sap Not sure if it helps here. But might be worth checking [react-testing library](https://testing-library.com/docs/react-testing-library/intro/) as we want to move away from enzyme anyway. See https://github.com/SAP/open-ux-tools/issues/833

2023-01-16 12:28 UTC, tom-sap commented
Hi @devinea, 
The testing framework looks better but looks like it's not possible after all to test the low level user interactions due to the browser behaviour.

Events created programmatically have [isTrusted](https://developer.mozilla.org/en-US/docs/Web/API/Event/isTrusted) set to false which changes the behaviour of the event, i.e. 
dispatching `keydown` event in an input does not affect the input value (which is what we need to test the feature).

Unless there are some hidden react hacks that would allow that, I have no more ideas :-)

2023-01-16 15:16 UTC, tom-sap commented
@Klaus-Keller @devinea can you review please?

2023-01-17 19:43 UTC, Klaus-Keller commented
Hi @tom-sap, 

Could you please add some information on what this PR exactly fixes and how to reproduce the issue? I've checked out this branch, built locally and tested table with validation in storybook, but I still see jumpy cursors:

![2023-01-17_11-35-33 (1)](https://user-images.githubusercontent.com/66327622/212995564-1d167b81-e92e-45a1-a0cd-9303424ac694.gif)

For instance when I delete the `e` in hello cursor jumps to the end or when I insert an `e` the same, cursor jumps to the end.

By the way, I think lines like e.g.:
https://sonarcloud.io/code?id=SAP_open-ux-tools&pullRequest=863&selected=SAP_open-ux-tools%3Apackages%2Fui-components%2Fsrc%2Fcomponents%2FUITable%2FUITable.tsx&line=135
https://sonarcloud.io/code?id=SAP_open-ux-tools&pullRequest=863&selected=SAP_open-ux-tools%3Apackages%2Fui-components%2Fsrc%2Fcomponents%2FUITable%2FUITable.tsx&line=153
https://sonarcloud.io/code?id=SAP_open-ux-tools&pullRequest=863&selected=SAP_open-ux-tools%3Apackages%2Fui-components%2Fsrc%2Fcomponents%2FUITable%2FUITable.tsx&line=174

could be covered by test cases without technical limitations.

2023-01-18 11:44 UTC, tom-sap commented
Hi @Klaus-Keller,

1. The description of the user interaction is in my previous comment: https://github.com/SAP/open-ux-tools/pull/863#issuecomment-1380550452

More details in the issue internal issue #21529.

2. If you were able to actually test this in Storybook, than you got further than me. For me Storybook was crashing whenever I wanted to edit the text. I tested the fix in DataEditor table and it works fine there (for me at least). I cannot say for storybook, as I cannot test this in storybook.

3. As I said before - this is a bug-fix-PR, rather than a back-filling-missing-unit-tests-TBI-PR, and something that should take 5 minutes already took (probably) 5 days. 
 
I will revert the refactoring so the only changes to the code is the lines that I've added.

2023-01-18 19:12 UTC, Klaus-Keller requested changes
Hi @tom-sap,

I found the reason why the fix did not work in storybook. I've tested with row 0 and this row was ignored due this condition twice in the code
```
if ( ... editedCell.rowIndex ...)
```
which resolves to `false` for row 0.

I also left a comment regarding cognitive complexity and added a test case in a separate PR.
Please check PR https://github.com/SAP/open-ux-tools/pull/869, if you agree we can merge it  into branch `jumping-cursor-in-edi-table`.

2023-01-18 19:12 UTC, Klaus-Keller commented on packages/ui-components/src/components/UITable/UITable.tsx
> +    // eslint-disable-next-line sonarjs/cognitive-complexity
We should not ignore this as the cognitive complexity exists and should be fixed.
If you do not want to address this with your fix, you could make sure that you do not increase the complexity.
See https://github.com/SAP/open-ux-tools/pull/869

2023-01-18 19:12 UTC, Klaus-Keller commented on packages/ui-components/src/components/UITable/UITable.tsx
> +            if (editedCell.rowIndex && editedCell?.column?.key) {
this condition causes row 0 to be ignored
https://github.com/SAP/open-ux-tools/pull/869

2023-01-19 10:51 UTC, tom-sap commented on packages/ui-components/src/components/UITable/UITable.tsx
> +        if (this.caretPosition !== -1 && editedCell?.rowIndex && editedCell.column?.key) {
good catch, thanks!

2023-01-19 10:57 UTC, tom-sap commented
Hi @Klaus-Keller,
The `rowIndex` condition was a good catch!
Somehow I never tested the first row 😊.

As for the test - this is an interesting approach, I must say.
It tests that the functions are called (so the coverage goes up) without actually testing the exact interaction :-)
(the issue didn't happen when the value was changed, but how it was changed)

Anyways, linters are happy, so all is fine now 😄 
Thanks for your help!

2023-01-19 12:12 UTC, 815are approved these changes

2023-01-19 12:16 UTC, oliversberzs approved these changes

2023-01-19 15:53 UTC, Klaus-Keller approved these changes
- Code looks good and is easy to understand
- Test coverage looks good
- Build and tested locally with Storybook

Approved from my side.

2023-01-20 09:29 UTC, merged