Feat/941/project access detect typescript
SAP/open-ux-tools pull request #942
Opened 2023-03-08 17:41 UTC by Klaus-Keller

### Issue
https://github.com/SAP/open-ux-tools/issues/941

Enhance `@sap-ux/project-acces` by functionality to detect the used programming language of an application: `JavaScript` | `TypeScript`.

2023-03-08 22:36 UTC, kranthie-sap requested changes
The helper function and changes to file search module look good and has good tests. 👍 
I have a suggestion for the helper and a request to export the type for the programming language.

2023-03-08 22:36 UTC, kranthie-sap commented on packages/project-access/src/index.ts
> +    getAppLanguage,
```suggestion
    getAppProgrammingLanguage,
```

I am wondering if app language could mean natural language. I can live with it though.

2023-03-08 22:36 UTC, kranthie-sap commented on packages/project-access/src/project/info.ts
> +    let appLanguage: 'JavaScript' | 'TypeScript' | '' = '';
Can we use and export this as a type? I am sure we will need to use something similar in the consumed tools code.

2023-03-08 23:45 UTC, kranthie-sap approved these changes

2023-03-10 07:40 UTC, tobiasqueck approved these changes
On first glance, it looked like quite a big change to solve the linked problem, however, keeping in mind that this generic `findByExtension` function is also usable for other cases in our tools e.g. to find all `xml` files, I am ok with this complex change
* code is well structured
* tests are easy to read and make clear what functionality is expected
* did not test locally 
* changeset looks good

2023-03-10 14:58 UTC, merged