TBI - refactor locate-reuse-lib.js template to use modern API's and fix lint issues
SAP/open-ux-tools pull request #966
Opened 2023-03-28 19:43 UTC by devinea

2023-03-31 13:30 UTC, korotkovao submitted a review, later dismissed

2023-04-05 14:57 UTC, IainSAP submitted a review, later dismissed
Thx @devinea 
- Tests updated as expected
- Did not test `locate-reuse-libs.js` changes, but verified that it was tested manually

2023-04-05 17:44 UTC, ullasholla commented on packages/ui5-application-writer/templates/optional/loadReuseLibs/webapp/test/locate-reuse-libs.js
> +                    url: "i18n/i18n.properties",
Typically, the resource bundles will be named `i18n/i18n.*properties`, but my understanding is that they don't _have_ to follow the naming convention. The authoritative place for the name would be the manifest. Do we need to handle the case where the resource bundle can't be located?

2023-04-05 17:45 UTC, ullasholla commented on packages/ui5-application-writer/templates/optional/loadReuseLibs/webapp/test/locate-reuse-libs.js
> +                            url: "i18n/i18n.properties",
Same comment as https://github.com/SAP/open-ux-tools/pull/966#discussion_r1158829801

2023-04-05 17:54 UTC, ullasholla commented
Does the file `locate-reuse-libs.js` need to turn strict mode on inside the functions? https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode

2023-04-05 17:59 UTC, ullasholla commented on packages/ui5-application-writer/templates/optional/loadReuseLibs/webapp/test/locate-reuse-libs.js
> +        Object.keys(dataFromAppIndex).forEach(function (moduleDefinitionKey) {
The check is done in the calling code: https://github.com/SAP/open-ux-tools/blob/e8b8cef411b7fbac9ef97525d0de4e385227c010/packages/ui5-application-writer/templates/optional/loadReuseLibs/webapp/test/locate-reuse-libs.js#L122-L123

Marking as resolved

2023-04-05 18:11 UTC, ullasholla requested changes
@devinea, thanks for the PR. The changes to `locate-reuse-libs.js` looks good. The tests are all correctly updated.

I have _not_ run the code and tested if it works as expected.

Had two questions:
* about using strict mode, https://github.com/SAP/open-ux-tools/pull/966#issuecomment-1497891444
* Handling resource bundle name mismatch (2 locations)

2023-04-05 18:13 UTC, devinea commented on packages/ui5-application-writer/templates/optional/loadReuseLibs/webapp/test/locate-reuse-libs.js
> +                            url: "i18n/i18n.properties",
see https://github.com/SAP/open-ux-tools/pull/966#discussion_r1158838857

2023-04-05 18:14 UTC, devinea commented
> Does the file `locate-reuse-libs.js` need to turn strict mode on inside the functions? https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode

@ullasholla good point. As discussed, I'll create a follow on PR for that next sprint.

2023-04-05 18:17 UTC, ullasholla commented on packages/ui5-application-writer/templates/optional/loadReuseLibs/webapp/test/locate-reuse-libs.js
> +                    url: "i18n/i18n.properties",
If they change the location/name, they'll have to update this file as well. Fair enough

2023-04-05 18:18 UTC, ullasholla approved these changes
All the review comments have been addressed. Thank you @devinea

2023-04-05 18:45 UTC, devinea commented
Thanks @korotkovao @IainSAP @ullasholla

2023-04-05 18:45 UTC, merged