tbi(ui5-writer): updates for update locate reuse lib
SAP/open-ux-tools pull request #970
Opened 2023-03-30 08:49 UTC by cianmSAP

https://github.com/SAP/open-ux-tools/issues/968

- Moves locate-reuse-lib.js to the webapp\test folder and ensure it is referenced from the flpSandbox.html file.
- Removes locate-reuse-lib.js reference from webapp\index.html file.

2023-03-30 15:18 UTC, devinea requested changes
@cianmSAP 1 change needed. 

Comments
`minor` for the changeset should be ok as there is no breaking change to the API. 
But `resourceroots` would need to be manually added in the `index.html` if the customer needs to load a reuse library later. 
`flpSandbox.html` will still dynamically load it from the frontend server (if needed and available) during local preview. In production the Fiori Launchpad will register the libraries neededs at runtime.

2023-03-30 19:10 UTC, cianmSAP commented on packages/ui5-application-writer/templates/core/webapp/index.html
>          data-sap-ui-frameOptions="trusted"
Updated

2023-03-31 08:46 UTC, devinea approved these changes
Thanks @cianmSAP 
Updates to templates and snapshots look good.
I did a quick test with `/packages/fiori-elements-writer/test/test-output/lropTemplates/lropV2` locally and `start` and `start-noflop` work well.

2023-03-31 12:29 UTC, IainSAP reviewed
Thx @cianmSAP 

- Paths updated as expected
- Test snapshots updated as expected

2023-03-31 12:29 UTC, IainSAP approved these changes

2023-03-31 13:07 UTC, merged