fix(env-check): ignore empty folders in archive
SAP/open-ux-tools pull request #994
Opened 2023-04-27 00:27 UTC by Klaus-Keller

See https://github.com/SAP/open-ux-tools/issues/993.

Adding option `mark: true` does the trick, it adds `/` to directories when comparing: https://github.com/kaelzhang/node-ignore#2-filenames-and-dirnames

2023-04-27 19:49 UTC, theStiggySpd approved these changes
- Changeset looks good
- Other relevant code change is good based on the explanation/link

Please note that I have not tested locally

2023-04-27 21:19 UTC, slin-sap requested changes
- Function signal changed only to an internal function. Thus CS level patch is correct. 
- Documentation of using mark: true is linked in the PR. 

This change to 3rd party library changes the behavior of getFileList function. But there is no unit test capture this behavior change. This might give opportunity to introduce regression.

2023-04-28 17:02 UTC, Klaus-Keller commented
> * Function signal changed only to an internal function. Thus CS level patch is correct.
> * Documentation of using mark: true is linked in the PR.
> 
> This change to 3rd party library changes the behavior of getFileList function. But there is no unit test capture this behavior change. E.g. If glob lib introduced a regression and mark: true doesn't take effect, there is no unit test can capture the issue.

@slin-sap, you are right, we mock `archiver` and `glob-gitignore` in the unit tests of this module. There are checks, whether `glob-gitignore` is called with correct parameters: 
- https://github.com/SAP/open-ux-tools/pull/994/files#diff-20d5dd809ed4daae5f2e90e7e1921b9bdd21e5acf4e53552fd3900330ea1236eR68
- https://github.com/SAP/open-ux-tools/pull/994/files#diff-20d5dd809ed4daae5f2e90e7e1921b9bdd21e5acf4e53552fd3900330ea1236eR118

but I agree, having no integration tests to check whether the correct files are selected using `glob-gitignore` and later archived in .zip file using `archiver` is a gap and should be added. I did a small tests, but adding integration tests blows up this PR and I'd prefer to address this as a separate task.

2023-04-28 17:05 UTC, slin-sap approved these changes
Agree testing the glob lib correctness is more appropriate in an integration test.

2023-04-28 17:06 UTC, merged