FPM writer: additional unit tests for contextPath
SAP/open-ux-tools pull request #995
Opened 2023-04-27 08:30 UTC by schreckstefan

Issue: https://github.com/SAP/open-ux-tools/issues/922

This PR provides additional unit tests, as required in https://github.com/SAP/open-ux-tools/pull/952#pullrequestreview-1401595864

2023-06-21 06:58 UTC, tobiasqueck commented
@schreckstefan what happened to this one? Is it obsolete or will you continue working on it?

2023-06-21 07:41 UTC, schreckstefan commented
@tobiasqueck 
@nlunets asked for it in my previous enhancement, thus I added the test and asked for a review.
Waiting for this since weeks...

2023-06-21 07:48 UTC, nlunets commented
At which point did you tag me ? :)

2023-06-21 07:50 UTC, nlunets commented on packages/fe-fpm-writer/test/unit/page/object.test.ts
> +                    contextPath: '/RootEntity/OtherEntity',
if the navigation is called to_OtherEntity the contextPath also needs to be /RootEntity/to_OtherEntity

2023-06-21 08:08 UTC, nlunets requested changes
this unit test is not 100% correct and i'm actually more worried about the part which generates the input you use for your test, where it that done ?

2023-08-14 11:04 UTC, schreckstefan commented
> 

@nlunets 
I corrected the test.

The logic for calculating the contextPath is not part of the FPM writer, it resides at the tools-suite:
<img width="889" alt="image" src="https://github.com/SAP/open-ux-tools/assets/126068396/5d59cf9f-22c5-4bb8-97f6-d3d483d06dd5">
It could be transferred to open-ux-tools, but I decided against doing the calculation inside the existing API, as it would require an incompatible enhancement of the given API functions: in order to detect the "mixed mode" at existing apps, carrying the entitySet at the parent node, I have to know the parent page,  plus potentially further information like the route pattern.
I could try to set up a separate helper function for the same, if you like. But would open a separate feature request for that.

2024-05-13 06:52 UTC, closed without merging